const crypto=require('node:crypto');const F=require('./finance.cjs');
function parseSchoolTables(tables){const entries=[],warnings=[];let ignored=0,recognized=0;for(const t of tables){const h=t.headers.map(x=>String(x).replace(/\s/g,''));const indexes={date:h.indexOf('创建时间'),name:h.findIndex(x=>x.includes('名称')&&x.includes('交易号')),place:h.indexOf('对方'),amount:h.findIndex(x=>x.includes('金额')),status:h.indexOf('状态')};if(Object.values(indexes).some(x=>x<0))continue;recognized++;
for(const row of t.rows){const value=k=>String(row[indexes[k]]||'').trim();const kind=value('name');if(value('status')!=='交易成功'||!/消费|退款|退费|冲正/.test(kind)||/充值|转账|补助|圈存/.test(kind)){ignored++;continue;}try{const id=kind.match(/交易号\s*[:：]\s*([\w-]+)/)?.[1];if(!id)throw Error('消费记录缺少交易号');const m=value('date').match(/(\d{4})[.\/-](\d{1,2})[.\/-](\d{1,2})/);if(!m)throw Error('消费记录日期无法识别');const date=`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;F.day(date);if(date>F.today())throw Error('消费日期晚于今天');let cents=Math.abs(F.cents(value('amount')));if(!cents){ignored++;continue;}if(/退款|退费|冲正/.test(kind))cents=-cents;const place=value('place');if(!place)throw Error('消费地点为空');const key=crypto.createHash('sha256').update('sustech:'+id).digest('hex');const meal=true;entries.push({id:'campus:'+key,key,date,place,cents,meal,source:'campus',sourceId:id,note:kind.split(/交易号/)[0].trim(),needsReview:false});}catch(e){warnings.push(e.message);}}
}return {entries,recognized,ignored,warnings:[...new Set(warnings)]};}
function collectPage(){const tables=Array.from(document.querySelectorAll('table')).filter(t=>t.getBoundingClientRect().height>0).map(t=>{const rows=Array.from(t.querySelectorAll('tr')).map(r=>Array.from(r.children).filter(c=>/^(TD|TH)$/.test(c.tagName)).map(c=>c.innerText.trim()));const header=rows.findIndex(r=>r.some(c=>c.includes('交易号'))&&r.some(c=>c.includes('创建时间')));return {headers:header<0?[]:rows[header],rows:header<0?[]:rows.slice(header+1)}});const page=document.body.innerText.match(/当前\s*(\d+)\s*\/\s*(\d+)\s*页/);return {tables,current:page?Number(page[1]):null,total:page?Number(page[2]):null,login:!!document.querySelector('input[type=password]')};}
function collectIdentity(){const m=document.body.innerText.match(/账号[：:]\s*(\d+)/);return m?m[1]:null;}
function clickNext(){const a=Array.from(document.querySelectorAll('a')).find(a=>a.innerText.trim()==='下一页'&&a.getBoundingClientRect().height>0);if(!a)return false;a.click();return true;}
const readPage='('+collectPage.toString()+')()',readIdentity='('+collectIdentity.toString()+')()',nextPage='('+clickNext.toString()+')()';
module.exports={parseSchoolTables,readPage,readIdentity,nextPage};
