const $=id=>document.getElementById(id),money=n=>'¥ '+(n/100).toFixed(2);let state,busy=false;
const text=(tag,value,cls)=>{const el=document.createElement(tag);el.textContent=value;if(cls)el.className=cls;return el;};
function status(message){$('status').hidden=!message;$('status').textContent=message;}
async function call(name,arg){const r=await window.wallet[name](arg);if(!r.ok)throw Error(r.error);return r.value;}
async function act(fn){if(busy)return;busy=true;try{await fn();}catch(e){status(e.message);}finally{busy=false;}}
function setView(name){document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==name);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('title').textContent={home:'餐费概览',records:'消费账单',budget:'预算计划',sync:'校园卡导入'}[name];}
async function refresh(){state=await call('load');const {book,stats:s,today}=state;$('date').textContent=today+' · 让每一顿饭心里有数';$('sustain').textContent=s.count?s.sustain??'—':'—';$('balance').textContent=money(s.balance);$('rate').textContent=s.count?`餐饮日均 ${money(s.rate)} · 统计 ${s.sampleDays} 个自然日`:'先导入账单或记录第一笔餐费';$('daily').textContent=s.daily===null?'已到期':money(s.daily);$('remaining').textContent=`到 ${book.settings.end}，还剩 ${s.remainingDays} 天（含今天）`;$('today-cost').textContent=money(s.todayCost);$('gap').textContent=!s.count||s.gap===null?'—':(s.gap>=0?'+ ':'− ')+money(Math.abs(s.gap));$('gap').className=s.gap<0?'negative':'positive';$('sample-note').textContent=s.sampleDays<7?'完整记账区间不足 7 天，预测可能波动较大。':'无消费日按 0 元计算；请确保这段时间没有漏记。';
 const ns='http://www.w3.org/2000/svg';$('chart').replaceChildren();const max=Math.max(...s.days.map(d=>Math.abs(d.cents)),100);s.days.forEach((d,i)=>{const v=document.createElementNS(ns,'rect');const height=Math.abs(d.cents)/max*145;for(const [k,val]of Object.entries({x:12+i*43,y:170-height,width:25,height:Math.max(1,height),rx:5,fill:d.cents<0?'#52b19c':i===13?'#3158e8':'#b7c9f8'}))v.setAttribute(k,val);const title=document.createElementNS(ns,'title');title.textContent=d.date+' '+money(d.cents);v.append(title);$('chart').append(v);if(i%3===0||i===13){const t=document.createElementNS(ns,'text');t.setAttribute('x',12+i*43);t.setAttribute('y',198);t.setAttribute('font-size',12);t.setAttribute('fill','#8794a8');t.textContent=d.date.slice(5);$('chart').append(t);}});
 $('places').replaceChildren();for(const p of s.places.slice(0,6)){const r=text('div','','place');r.append(text('span',p.name),text('small',`${p.count} 次 · ${money(p.cents)}`));$('places').append(r);}if(!s.places.length)$('places').append(text('p','还没有餐饮记录。\n导入账单后，会在这里展示常去的地方。','empty'));
 for(const [id,key]of Object.entries({anchor:'anchor',end:'end','sample-start':'sampleStart'}))$(id).value=book.settings[key];$('funds').value=(book.settings.funds/100).toFixed(2);$('budget-amount').value=(book.settings.budget/100).toFixed(2);$('anchor').max=today;$('sample-start').max=today;$('entry-date').max=today;renderRecords();}
let recordMode='flow',selectedPlace=null;
function switchRecords(mode){recordMode=mode;renderRecords();}
function renderRecords(){
 const q=$('search').value.trim();
 const entries=state.book.entries.filter(e=>(e.date+e.place).includes(q)&&(!selectedPlace||e.place===selectedPlace));
 $('flow-panel').hidden=recordMode!=='flow';$('locations-panel').hidden=recordMode!=='locations';
 for(const [id,mode] of [['show-flow','flow'],['show-locations','locations']]){$(id).classList.toggle('active',recordMode===mode);$(id).setAttribute('aria-pressed',String(recordMode===mode));}
 $('records-summary').replaceChildren(text('span',`${selectedPlace?selectedPlace+' · ':''}共 ${entries.length} 笔记录 · 净支出 ${money(entries.reduce((sum,e)=>sum+e.cents,0))} `));
 if(selectedPlace){const clear=text('button','查看全部地点');clear.onclick=()=>{selectedPlace=null;renderRecords();};$('records-summary').append(clear);}
 $('records-body').replaceChildren();
 for(const e of [...entries].sort((a,b)=>b.date.localeCompare(a.date))){const tr=document.createElement('tr');tr.append(text('td',e.date),text('td',e.place),text('td',money(e.cents)));const td=document.createElement('td'),c=document.createElement('input');c.type='checkbox';c.checked=e.meal;c.setAttribute('aria-label',e.place+'计入餐饮');c.onchange=()=>act(async()=>{await call('toggle',e.id);await refresh();});td.append(c);tr.append(td,text('td',e.source==='campus'?'校园卡':'手动'));const del=text('button','删除');del.onclick=()=>{if(confirm('删除这笔记录？已导入记录的去重标记会保留。'))act(async()=>{await call('remove',e.id);await refresh();});};const end=document.createElement('td');end.append(del);tr.append(end);$('records-body').append(tr);}
 const places=new Map();
 for(const e of entries){if(!places.has(e.place))places.set(e.place,{name:e.place,count:0,spent:0,refund:0});const p=places.get(e.place);if(e.cents>=0){p.count++;p.spent+=e.cents;}else p.refund-=e.cents;}
 $('locations-body').replaceChildren();
 for(const p of [...places.values()].sort((a,b)=>(b.spent-b.refund)-(a.spent-a.refund)||a.name.localeCompare(b.name,'zh-CN'))){const row=document.createElement('tr');row.append(text('td',p.name),text('td',p.count+' 次'),text('td',money(p.spent)),text('td',money(p.refund)),text('td',money(p.spent-p.refund)),text('td',p.count?money(p.spent/p.count):'—'));const td=document.createElement('td'),button=text('button','查看流水');button.setAttribute('aria-label','查看'+p.name+'的流水');button.onclick=()=>{selectedPlace=p.name;switchRecords('flow');};td.append(button);row.append(td);$('locations-body').append(row);}
 if(!entries.length)for(const [id,cols] of [['records-body',6],['locations-body',7]]){const tr=document.createElement('tr'),td=text('td',state.book.entries.length?'没有符合条件的记录。':'暂无账单。可先打开校园卡网站读取明细。');td.colSpan=cols;tr.append(td);$(id).append(tr);}
}
$('show-flow').onclick=()=>switchRecords('flow');$('show-locations').onclick=()=>{selectedPlace=null;switchRecords('locations');};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('search').oninput=()=>{selectedPlace=null;renderRecords();};$('add-open').onclick=()=>{$('entry-date').value=state.today;$('entry-dialog').showModal();};$('cancel').onclick=()=>$('entry-dialog').close();$('entry-form').onsubmit=e=>{e.preventDefault();act(async()=>{await call('add',{date:$('entry-date').value,place:$('entry-place').value,amount:$('entry-amount').value});$('entry-dialog').close();$('entry-form').reset();await refresh();status('餐费已保存');});};
$('settings-form').onsubmit=e=>{e.preventDefault();act(async()=>{await call('settings',{funds:Math.round(Number($('funds').value)*100),budget:Math.round(Number($('budget-amount').value)*100),anchor:$('anchor').value,end:$('end').value,sampleStart:$('sample-start').value});await refresh();status('预算计划已保存');});};
$('school').onclick=()=>act(async()=>{status('正在打开学校官方登录窗口…');await call('school');status('请在学校窗口完成登录，然后返回点击一键同步账单。');});
$('scan').onclick=()=>act(async()=>{status('正在同步学校账单…');$('scan').disabled=true;$('cancel-sync').hidden=false;try{const r=await call('scan');await refresh();status(`同步完成：读取 ${r.pages} 页，新增 ${r.added} 笔，跳过 ${r.duplicates} 笔重复记录。${r.unclassified} 笔非餐饮或待分类，请在账单页核对。`);$('scan-info').textContent=`最近同步：${new Date().toLocaleString()} · ${r.count} 条消费与退款`;setView('home');}finally{$('scan').disabled=false;$('cancel-sync').hidden=true;}});
$('cancel-sync').onclick=async()=>{await call('cancelSync');status('正在取消同步…');};
window.syncEvents.onProgress(message=>status(message));
$('backup').onclick=()=>act(async()=>{if(await call('backup'))status('备份已导出');});$('restore').onclick=()=>act(async()=>{if(await call('restore')){await refresh();status('账本已恢复');}});act(refresh);
